apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: morning-hello
  labels:
    expect: succeeded
spec:
  steps:
  - name: test
    image: gcr.io/cloud-builders/docker
    # Test pulling a private builder container.
    args: ["pull", "aimbot31/test-knative-ol"]
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
      type: Socket